syntax = "proto3";

option csharp_namespace = "AccountService.API.Grpc.Service";

package accountAuthenticationService;
import "google/api/annotations.proto";

service AccountAuthenticationService {
    rpc Login(UserLogin) returns (TokenResponse) {
        option (google.api.http) = {
            post: "/v1/login"
        };
    };

    rpc Register(UserRegistry) returns (RegisterResponse) {
        option (google.api.http) = {
            post: "/v1/register"
        };
    };

    rpc RefreshToken(RefreshTokenModel) returns (TokenResponse) {
        option (google.api.http) = {
            post: "/v1/refresh-token"
        };
    }
}

message UserLogin {
  string email = 1;
  string password = 2;
  bool rememberLogin = 3;
}

message RefreshTokenModel {
	string token = 1;
}

message UserRegistry {
   string userName = 1;
   string password = 2;
   string firstName = 3;
   string middleName = 4;
   string lastName = 5;
   string phoneNumber = 6;
   string email = 7;
   string returnUrl = 8;
}

message RegisterResponse {
	UserRegistry user = 1;
}

message TokenResponse {
  string access_token = 1;
  string refresh_token = 2;
  string user_id = 3;
}